config/routes.rb
Rails.application.routes.draw do
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  root 'welcome#index'
  get 'sign_up' => 'users#new'
  resources :users, only: :create

  resources :sessions, only: :create
  delete 'logout' => 'sessions#destroy'
  get    'login'  => 'sessions#new'

  resources :notes, except: :edit

  namespace :api do
    namespace :v1 do
      resources :notes, except: [:new, :edit]
    end
  end
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :user
  validates :title, presence: true, length: { maximum: 200 }
  default_scope { order('updated_at DESC') }
  scope :ordered, -> { order('created_at DESC') }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :notes
  validates :password, length: { minimum: 8 }, on: :create
  validates :username, presence: true, uniqueness: true
  validate :passwords_match

  before_create :generate_api_key

  def display_name
    name.presence || username
  end

  def generate_api_key
    self.api_key = BCrypt::Password.create(password_digest)
  end

  private

  def passwords_match
    if password.present? && password != password_confirmation
      errors.add :password_confirmation, 'must match the password'
    end
  end
end

app/controllers/api/v1/api_controller.rb
class API::V1::APIController < ApplicationController
  skip_before_action :verify_authenticity_token

  protected

  def authorize_api_key
    unless current_api_user.present?
      render nothing: true, status: :unauthorized
    end
  end

  private

  def current_api_user
    if params[:api_key]
      @current_api_user ||= User.find_by(api_key: params[:api_key])
    end
  end
end

app/controllers/api/v1/notes_controller.rb
class API::V1::NotesController < API::V1::APIController
  before_action :authorize_api_key

  def index
    @notes = current_api_user.notes.ordered
    respond_to :json
  end

  def show
    @note = current_api_user.notes.find params[:id]
    respond_to :json
  end

  def create
    @note = current_api_user.notes.build note_params
    if @note.save
      render :show
    else
      render json: note.errors, status: :unprocessable_entity
    end
  end

  private

  def note_params
    params.require(:note).permit(:title, :body_html)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  protected

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authorize_user
    if current_user.nil?
      redirect_to login_path, :'alert-danger' => t('session.flash.unauthenticated')
    end
  end

  def load_notes
    @notes = current_user.notes.all if current_user.present?
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :authorize_user
  before_action :load_notes
  before_action :find_note, only: [:show, :edit, :update, :destroy]

  def show
    render :edit
  end

  def new
    @note = current_user.notes.new
  end

  def create
    @note = current_user.notes.new note_params
    set_flash_for @note.save
    render_or_redirect
  end

  def update
    set_flash_for @note.update(note_params)
    render_or_redirect
  end

  def destroy
    set_flash_for @note.destroy
    render_or_redirect
  end

  private

  def find_note
    @note = Note.find params[:id]
  end

  def note_params
    params.require(:note).permit(:title, :body_html)
  end

  def set_flash_for(action_result)
    if action_result
      flash[:'alert-success'] = t("note.flash.#{action_name}.success")
    else
      flash.now[:'alert-danger'] = t("note.flash.#{action_name}.failure")
    end
  end

  def render_or_redirect
    if @note.errors.any?
      render :edit
    else
      redirect_to redirection_path
    end
  end

  def redirection_path
    return @note if @note.persisted?
    new_note_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  layout 'landing'

  def new
    @user = User.new
  end

  def create
    user = User.find_by username: user_params[:username]
    if user.present? && user.authenticate(user_params[:password])
      session[:user_id] = user.id
      redirect_to root_url, :'alert-success' => t('session.flash.create.success')
    else
      @user = User.new username: user_params[:username]
      flash.now[:'alert-danger'] = t('session.flash.create.failure')
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :'alert-success' => t('session.flash.destroy.success')
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout 'landing'

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, :'alert-success' => t('user.flash.create.success')
    else
      flash.now[:'alert-danger'] = t('user.flash.create.failure')
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :name, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authorize_user

  def index
    redirect_to new_note_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_messages(flash)
    flash.map do |name, msg|
      content_tag :div, class: "alert #{name}" do
        flash_message_output msg
      end
    end.join.html_safe
  end

  def flash_message_output(content)
    if content.is_a? Array
      flash_list content
    else
      content
    end
  end

  def flash_list(messages)
    content_tag :ul do
      messages.map do |message|
        content_tag(:li, message)
      end.join.html_safe
    end
  end

  def title_autofocus?(note)
    note.new_record?
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Elevennote
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    .container.wrap
      .row
        .col-xs-12
          %header
            .well
              Nevernote
              .user-links
                - if current_user.present?
                  Signed in as #{current_user.display_name}.
                  = link_to 'Logout', logout_path, method: :delete
                - else
                  = link_to 'Sign Up', sign_up_path
                  or
                  = link_to 'Login', login_path
        .container
          .row
            .col-xs-4
              %nav#sidebar
                = link_to new_note_path, class: 'new-note btn btn-default' do
                  %i.fa.fa-plus-circle
                  New Note
                = render 'notes/list', notes: @notes
            .col-xs-8
              %main
                = flash_messages(flash)
                = yield

app/views/layouts/landing.html.haml
!!!
%html
  %head
    %title Nevernote
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body#welcome
    .container.wrap
      .row
        .col-xs-12
          %header
            .well
              Nevernote
        .container
          .row
            .col-xs-12
              %main
                = flash_messages(flash)
                = yield

app/views/notes/_form.html.haml
= form_for note do |f|
  %p
    = f.text_field :title, placeholder: t('note.placeholder.title'), autofocus: title_autofocus?(f.object)
  %p
    = f.bootsy_area :body_html, placeholder: t('note.placeholder.body')
  .form-actions
    = f.submit class: 'btn btn-default'
    - if note.persisted?
      = link_to note, method: :delete, data: { confirm: 'Are you sure? This cannot be undone' } do
        %i.fa.fa-trash-o

app/views/notes/_list.html.haml
- if notes.present?
  %ul#notes
    - notes.each do |note|
      %li{"data-url" => note_path(note)}
        = content_tag :div, note.title, class: 'note-title'
        = content_tag :div, note.body_html.to_s.html_safe, class: 'note-body'

app/views/notes/edit.html.haml
= render 'form', note: @note

app/views/notes/new.html.haml
= render 'form', note: @note

app/views/users/new.html.haml
%h3 Sign Up for ElevenNote
= form_for @user do |f|
  %p
    = f.label :name
    %br/
    = f.text_field :name
  %p
    = f.label :username
    %br/
    = f.text_field :username
  %p
    = f.label :password
    %br/
    = f.password_field :password
  %p
    = f.label :password_confirmation
    %br/
    = f.password_field :password_confirmation
  = f.submit 'Sign Up', class: 'btn btn-default'
  %span.login
    Already have an account? #{link_to 'Sign in', login_path}.